### PR TITLE
Iris Flowers Demo

### PR DESCRIPTION
**Pull request by dkorolev**
@mzhurovich, PTAL.

Mostly as an example and a reference point of what more can/should we simplify API-wise.

Thanks!
Dima

### CODE REVIEW

**Comment by dkorolev** [comment]
@sompylasar -- зацени :-)

**Comment by dkorolev** [comment]
Hi @mzhurovich & @sompylasar 

PTAL -- best after https://github.com/KnowSheet/Sherlock/pull/29 is merged.

Thanks!
Dima

**Comment by dkorolev** [comment]
(FTR: The test passes on Mac, but, when running the code for real, the rendering part doesn't have the `pngcairo` visualizer. Fine for now.)

**Comment by sompylasar** [comment]
@dkorolev API или библиотека познаётся тогда, когда пытаешься использовать иначе, чем задумал разработчик.

**Comment by dkorolev** [comment]
@sompylasar Пока всё плюс-минус по назначению, кромe HTML.

**Comment by dkorolev** [comment]
@mzhurovich PTAL (after https://github.com/KnowSheet/Sherlock/pull/29)

Thanks!
Dima

**Comment by dkorolev** [comment]
Merged changes from https://github.com/KnowSheet/Sherlock/pull/29, this one is ready to look at again!

**Comment by mzhurovich** [comment]
@dkorolev LGTM++!
Need another round of discussions about simple API vs Accessor/Mutator syntax :)

**Comment by dkorolev** [comment]
Thanks @mzhurovich !

Have a great night -- and talk soon!

Dima

**Comment by dkorolev** [comment]
@mzhurovich -- please hold on for a sec with this pull request, HTTP subscription got broken.

It's blocking me, and it might be something bigger. Investigating now. Please review https://github.com/KnowSheet/Sherlock/pull/30 in the meantime once you have a minute.

Thanks!
Dima

**Comment by dkorolev** [comment]
Well, obviously -- stream publishing is now temporarily disabled. That explains a lot! Looking into ...

**Comment by dkorolev** [comment]
@mzhurovich : PTAL at this one as well..

Commits history is f**cked up here; we'll re-create pull request with one commit.

Please take a look -- but don't click "Merge". Thanks! :-)

**Comment by dkorolev** [comment]
@mzhurovich : I'll re-push this code once the current changes are in. Omitting this pull request now.

**Pull request closed without merging**
