### PR TITLE
Tested exposing streams via HTTP.

### PR DESCRIPTION
**Pull request by dkorolev**
No deadlocks, as tested via `./.noshit/test --gtest_repeat=1000`

### CODE REVIEW

**Comment by dkorolev** [comment]
Confirmed no deadlocks on Mac as well.

**Comment by dkorolev** [comment]
Tested from Mac -- works like a Swiss watch.

@mzhurovich : PTAL!

**Comment by dkorolev** [comment]
Also, I suggest we rename `T_CONTAINER_WRAPPER cw` into `T_DATA data`. And the world shall be at peace.

**Comment by dkorolev** [comment]
@mzhurovich : Thanks and PTAL!

**Comment by mzhurovich** [comment]
@dkorolev :+1:

**Comment by dkorolev** [comment]
:+1: Yay, thank you!

**Pull request merged**
