### PR TITLE
Yoda RC 1.

### PR DESCRIPTION
**Pull request by dkorolev**
Hi @mzhurovich,

We have the first Yoda Release Candidate.

Please review after:
1. https://github.com/KnowSheet/Bricks/pull/170
2. https://github.com/KnowSheet/Sherlock/pull/37

Talk in ~6.5 hours.

Thanks!
Dima

### CODE REVIEW

**Comment by mzhurovich** [comment]
@dkorolev FTR, this version doesn't compile on Mac without the following addition to the `Container` of matrix:
`YET operator()(type_inference::template YETFromK<std::tuple<const typename YET::T_ROW&, const typename YET::T_COL&>>);`

**Comment by dkorolev** [comment]
@mzhurovich : Minor comments answered+addressed.

Also renamed `KeyEntry` into `Dictionary`, now as it all makes sense -- please let me know whether it does to your eye.

Looking into compilation problems with two computers next to me now.

**Comment by dkorolev** [comment]
@mzhurovich 

Re:

```
@dkorolev FTR, this version doesn't compile on Mac without the following addition to the Container of matrix:
YET operator()(type_inference::template YETFromK<std::tuple<const typename YET::T_ROW&, const typename YET::T_COL&>>);
```

I identified the problem and spent ~10 minutes narrowing it down on Mac until realizing that the change is to `git pull` in `../../Bricks` :+1: 

The `YO DAWG!` change takes care of this `const KEY&` -> `KEY` as part of `std::tuple<>` thing, where it first declares the type `SAFE_KEY` via `rmcontsref<>` before applying `CWT`.

Long live C++!

**Comment by mzhurovich** [comment]
@dkorolev Everything is great! :+1: 
Ironically, I already thought of the same renaming of `KeyEntry`, so we are on the same page here :)
And sorry again for my midnight comments that turned out to be not relevant :(

**Pull request merged**
